name: matrix build and deploy

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  matrix_deploy:
    strategy:
      matrix:
        target: [staging, prod]
    steps:
      - uses: yikaicao/hn-demo/.github/workflows/deploy.yml@main
        with:
          destination-target: ${{ matrix.target }}
