name: matrix build and deploy

on:
  workflow_dispatch:

jobs:
  matrix_deploy:
    strategy:
      matrix:
        target: [staging, prod]
    uses: yikaicao/hn-demo/.github/workflows/deploy.yml@main
    with:
      dest-target: ${{ matrix.param }}
    secrets: inherit
