name: matrix build and deploy

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  matrix_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [staging, prod]
    uses: yikaicao/hn-demo/.github/workflows/deploy.yml@main
    with:
      dest-target: ${{ matrix.param }}