name: matrix build and deploy

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:

  matrix_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [staging, prod]
    uses: ./.github/workflows/deploy.yml
    with:
        node-version: ${{ matrix.target }}