name: matrix build and deploy

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  matrix_deploy:
    strategy:
      matrix:
        param: [staging, prod]
    uses: yikaicao/hn-demo/.github/workflows/deploy.yml@main
    with:
      param: ${{ matrix.param }}
