name: ansible-eb-test-and-deployment

on:
  push:
    branches:
      - "main"
  workflow_call:
    inputs:
      dest-target:
        required: true
        type: string
        default: staging
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: nothing
        run: echo hello

  deploy-prod:
    needs: [build]
    if: ${{ inputs.dest-target == 'prod' }}
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: yikaicao/yikai-spring-demos
          token: ${{secrets.gh_actions}}
          persist-credentials: false
      - name: install ansible
        run: |
          sudo apt-add-repository ppa:ansible/ansible
          sudo apt update
          sudo apt-get install -y ansible
          ansible-playbook --version
      - name: install eb-cli
        run: |
          curl -O https://bootstrap.pypa.io/get-pip.py
          python3 get-pip.py --user
          pip install awsebcli --upgrade --user
          eb --version
      - name: print dummy token
        if: ${{ contains(github.ref, 'staging') }}
        run: echo ${{ secrets.DuMMy_tOken }}

  deploy-staging:
    needs: [build]
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: checkout this repo
        uses: actions/checkout@v3
        with:
          path: current_repo
      - name: get workspace
        working-directory: current_repo
        run: |
          ls
          ls pom.xml
          echo "workspace=$(pwd)"
          echo "workspace=$(pwd)" >> $GITHUB_ENV
      - name: checkout dependencies
        uses: actions/checkout@v3
        with:
          repository: yikaicao/yikai-spring-demos
          token: ${{secrets.gh_actions}}
          persist-credentials: false
          path: my_tools
      - name: where am I??
        run: |
          pwd
          ls ../current_repo/
          ls
          ls pom.xml
          ls ../
      - name: where am I?
        run: |
          mvn_home=$(which mvn)
          workspace=${{ env.workspace }}
          echo ${mvn_home}
          echo $mvn_home
          echo ${workspace}
          echo $workspace
          ls
          ls -l | wc
          echo ${{ secrets.dummy_token }}
          echo ${{ inputs.dest-target }}
          mvn package -Dfile=$workspace
#      - name: install ansible
#        run: |
#          sudo apt-add-repository ppa:ansible/ansible
#          sudo apt update
#          sudo apt-get install -y ansible
#          ansible-playbook --version
#      - name: install eb-cli
#        run: |
#          curl -O https://bootstrap.pypa.io/get-pip.py
#          python3 get-pip.py --user
#          pip install awsebcli --upgrade --user
#          eb --version
#      - name: print dummy token
#        working-directory: yikai-spring-demos/
#        run: |
#          echo ${{ secrets.dummy_token }}
#          echo ${{ inputs.dest-target }}
#          ls -l | wc
