name: ansible-eb-deployment

on:
  push:
    branches:
      - "main"
  workflow_call:
  workflow_dispatch:

jobs:
  deploy-prod:
    if: ${{ contains(github.ref, 'main') }}
    environment: prod
    runs-on: ubuntu-latest
    steps:  
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: yikaicao/yikai-spring-demos
          token: ${{secrets.gh_actions}}
          persist-credentials: false
      - name: install ansible
        run: |
          sudo apt-add-repository ppa:ansible/ansible
          sudo apt update
          sudo apt-get install -y ansible
          ansible-playbook --version
      - name: install eb-cli
        run: |
          curl -O https://bootstrap.pypa.io/get-pip.py
          python3 get-pip.py --user
          pip install awsebcli --upgrade --user
          eb --version
      - name: print dummy token
        if: ${{ contains(github.ref, 'staging') }}
        env: 
        run: echo ${{ secrets.DuMMy_tOken }}

  deploy-staging:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: yikaicao/yikai-spring-demos
          token: ${{secrets.gh_actions}}
          persist-credentials: false
      - name: install ansible
        run: |
          sudo apt-add-repository ppa:ansible/ansible
          sudo apt update
          sudo apt-get install -y ansible
          ansible-playbook --version
      - name: install eb-cli
        run: |
          curl -O https://bootstrap.pypa.io/get-pip.py
          python3 get-pip.py --user
          pip install awsebcli --upgrade --user
          eb --version
      - name: print dummy token
        run: echo ${{ secrets.dummy_token }}
