name: custom-deployyment

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: add ansible package archive
        run: sudo apt-add-repository ppa:ansible/ansible
      - name: update system package index
        run: sudo apt update
      - name: install ansible
        run: sudo apt-get install -y ansible
      - name: check ansible version
        run: ansible-playbook --version
