name: ansible-eb-deployment

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install ansible
        run: |
          sudo apt-add-repository ppa:ansible/ansible
          sudo apt update
          sudo apt-get install -y ansible
          check ansible version
          ansible-playbook --version
      - name: install eb-cli
        run: |
          curl -O https://bootstrap.pypa.io/get-pip.py
          python3 get-pip.py --user
          eb --version
